"""Fix Table model to Crop

Revision ID: e740b9d6ff16
Revises: 
Create Date: 2025-01-25 19:59:54.262150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e740b9d6ff16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('land', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('crops_type', sa.String(), nullable=False),
    sa.Column('crops_quantity', sa.Float(), nullable=False),
    sa.Column('crops_price', sa.Float(), nullable=False),
    sa.Column('crops_quality', sa.String(), nullable=False),
    sa.Column('crops_location', sa.String(), nullable=False),
    sa.Column('crops_date', sa.DateTime(), nullable=True),
    sa.Column('crops_farmer', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crops_farmer'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops')
    op.drop_table('farmer')
    # ### end Alembic commands ###
