# Generated by Django 5.2.8 on 2025-12-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
